# Generated by Django 4.2.7 on 2023-12-27 11:14

import MyApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media', validators=[MyApp.validators.file_size]),
        ),
    ]
