# Generated by Django 4.2.7 on 2023-12-27 11:17

import MyApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos', validators=[MyApp.validators.file_size]),
        ),
    ]
