# Generated by Django 4.2.7 on 2024-01-04 12:22

import MyApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='', validators=[MyApp.validators.file_size]),
        ),
    ]
